[package]
name = "rinku"
version = "0.1.0"
authors = ["Anton Rybakov <'anryoshi@gmail.com'>"]
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
strum = "0.24"
strum_macros = "0.24"
dirs = "4.0"
